export enum SyntaxKind {
  BadToken,
  CloseParenthesisToken,
  ColonEqualToken,
  CommaToken,
  DotToken,
  EOFToken,
  EqualToken,
  GreaterThanToken,
  GreaterThanEqualToken,
  HashToken,
  LessThanToken,
  LessThanEqualToken,
  MinusToken,
  OpenParenthesisToken,
  PlusToken,
  SemicolonToken,
  SlashToken,
  StarToken,
  QuestionToken,
  
  BeginKeyword,
  CallKeyword,
  ConstKeyword,
  DoKeyword,
  EndKeyword,
  IfKeyword,
  OddKeyword,
  ProcedureKeyword,
  ThenKeyword,
  WhileKeyword,
  VarKeyword,

  NumericLiteral,

  Identifier,

  NewlineTrivia,
  WhitespaceTrivia,
}